### ISSUE TITLE
Toolbar protrudes through windows

### ISSUE THREAD

**Issue by hartolit** [kubagosth/JGToolbar#3]
**Bug**
When opening file explorer and shifting to a new window. The toolbar protrudes through the new window blocking access to functionality. (See pictures)

**To Reproduce**
1. Open file explorer
2. Shift to a new window and go fullscreen
3. Toolbar protrudes through window

**Screenshots**
![image](https://github.com/user-attachments/assets/13d9ba60-d8d3-40bb-9a32-930de4e5b9b0)
![image](https://github.com/user-attachments/assets/c7d5bc6c-8b6a-42a4-a37f-9483be856e93)

**Desktop:**
 - OS: Windows 11
 - Version: 23H2

**Comment by kubagosth** [comment]
Fixed [126d021](https://github.com/kubagosth/JGToolbar/commit/126d021029a071a83e9dd307dd79e4fbab81a2ae)
